### PR TITLE
Set password authentification to scram-sha-256

### PR DESCRIPTION
**Pull request by NyakudyaA**
* add env variable for password auth https://www.postgresql.org/docs/12/auth-password.html

### CODE REVIEW

**Comment by lucernae** [comment]
LGTM. I will check why the build failed.

**Comment by lucernae** [comment]
This is the error:
It happens when we create a new datadir (applying new pg_hba)
```
Add rule to pg_hba: 0.0.0.0/0
Add rule to pg_hba: replication replicator 
Setup master database
Initializing Postgres Database at /var/lib/postgresql/12/main
Initializing with command:
initdb: error: must specify a password for the superuser to enable scram-sha-256 authentication
```

**Comment by lucernae** [comment]
@NyakudyaA maybe we should not make this a default choice?

https://stackoverflow.com/questions/53397531/how-to-use-scram-sha-256-in-postgres-10-in-debian-getting-fatal-password-auth

The default auth used by postgres in the build phase is `md5` that means if we want to use scram as default, the user setup needs to be done after entrypoint.

**Comment by NyakudyaA** [comment]
> @NyakudyaA maybe we should not make this a default choice?
> 
> https://stackoverflow.com/questions/53397531/how-to-use-scram-sha-256-in-postgres-10-in-debian-getting-fatal-password-auth
> 
> The default auth used by postgres in the build phase is `md5` that means if we want to use scram as default, the user setup needs to be done after entrypoint.

let me adjust my PR. I will remove the parameters for initialization in the cluster generation and just let the password creation default to  `scram-sha-256`. This should work.

I just wanted to test what would happen if the cluster uses MD5 and the user chooses scam-sha-256

Alternatively, we can provide the password to initdb since this is done by superuser we have in the

**Comment by lucernae** [comment]
> let me adjust my PR. I will remove the parameters for initialization in the cluster generation and just let the password creation default to scram-sha-256. This should work.

If I read it correctly from the articles, this will work, but existing user (previously with md5 pass) will not be able to login anymore unless their password was reset by the superuser. We need to incorporate that into the readme as well since it will invalidate all passwords in the current cluster.

If we want to make this a default option for the auth, we have to put it in the Dockerfile too, because postgres won't know that we changed the auth scheme when building the image (md5 currently) vs running the image (targeted to use scram).

Lastly, I tried the unittest, it failed because you can't just pass the auth options to initdb. The error line is here:
```
initdb: error: must specify a password for the superuser to enable scram-sha-256 authentication
```
Currently, I don't understand if the error means the `postgres` unix user, or `postgres` database user that needs to have password first in order for this to work.

**Comment by NyakudyaA** [comment]
> > let me adjust my PR. I will remove the parameters for initialization in the cluster generation and just let the password creation default to scram-sha-256. This should work.
> 
> If I read it correctly from the articles, this will work, but existing user (previously with md5 pass) will not be able to login anymore unless their password was reset by the superuser. We need to incorporate that into the readme as well since it will invalidate all passwords in the current cluster.
> 
> If we want to make this a default option for the auth, we have to put it in the Dockerfile too, because postgres won't know that we changed the auth scheme when building the image (md5 currently) vs running the image (targeted to use scram).
> 
> Lastly, I tried the unittest, it failed because you can't just pass the auth options to initdb. The error line is here:
> 
> ```
> initdb: error: must specify a password for the superuser to enable scram-sha-256 authentication
> ```
> 
> Currently, I don't understand if the error means the `postgres` unix user, or `postgres` database user that needs to have password first in order for this to work.

I will default the auth to MD5 and anyone wanting to use `scram` can do so on their own. 

Some reference @lucernae  https://github.com/docker-library/postgres/pull/493/files

**Comment by NyakudyaA** [comment]
@lucernae i have fixed the script. Just take a look again

**Comment by lucernae** [comment]
LGTM for me.
Do you have any article that shows use case on how to use scram? we might want to create a scenario tests. I tried googling the error about superuser password, but still haven't found any clue.

**Comment by NyakudyaA** [comment]
> LGTM for me.
> Do you have any article that shows use case on how to use scram? we might want to create a scenario tests. I tried googling the error about superuser password, but still haven't found any clue.

Here are some references
https://info.crunchydata.com/blog/how-to-upgrade-postgresql-passwords-to-scram
https://www.pgcon.org/2019/schedule/attachments/530_scram.pdf
https://paquier.xyz/postgresql-2/postgres-10-scram-authentication/

**Pull request merged**
