### PR TITLE
Feature/extension h3

### PR DESCRIPTION
**Pull request by Martenz**
Based on this tutorial 

https://blog.rustprooflabs.com/2023/05/postgis-h3-v4-refresh
and previous
https://blog.rustprooflabs.com/2022/04/postgis-h3-intro

I added to my local image the h3 extension for Uber-h3 cells postgis functions. 

Which depends on 

https://github.com/zachasme/h3-pg

the library installation needs pgxn client and make > 3.20 installed so I modified the docker file accordingly.

Do you think it will be possible to include this library in the develop and next release of available docker images? 

I already tested it in local adding the extension to the env var:

      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting,h3,h3_postgis

and it works.

you can test it running the following query once container is up:

SELECT extname, extversion
    FROM pg_catalog.pg_extension 
    WHERE extname IN ('h3', 'h3_postgis')
;

### CODE REVIEW

**Comment by NyakudyaA** [comment]
Ping @Martenz

**Comment by mbforr** [comment]
just wanted to check to see if there are any plans to have this merged in?

**Comment by NyakudyaA** [comment]
> just wanted to check to see if there are any plans to have this merged in?

@mbforr please address the review comments and then we can merge

**Review by mbforr — APPROVED** [review]
Tested it locally and all works on my end!

**Comment by mbforr** [comment]
@NyakudyaA let me know if that works for you - thanks!

**Comment by NyakudyaA** [comment]
@Martenz Can you give this one test run and then we merge

**Comment by mbforr** [comment]
@NyakudyaA hey so the edits here and here:

https://github.com/kartoza/docker-postgis/pull/428/commits/10d88541eed8ba04a08bf046903a56e3c044e051#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L143

https://github.com/kartoza/docker-postgis/pull/428/commits/10d88541eed8ba04a08bf046903a56e3c044e051#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L61

actually removed the install for h3. would it make sense to add those back to a new PR to add them in?

**Comment by NyakudyaA** [comment]
cmake is installed here https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile#L26
h3 is installed here https://github.com/kartoza/docker-postgis/blob/develop/Dockerfile#L111

Have you actually tested the image?

**Comment by NyakudyaA** [comment]
@Martenz 

image

**Comment by mbforr** [comment]
my fault! was running the old one but this works thanks all!

**Pull request merged**
