### PR TITLE
add TOC 

### PR DESCRIPTION
**Pull request by NyakudyaA**
* Add TOC 
* Fix SSL permissions when mounting them

### CODE REVIEW

**Comment by NyakudyaA** [comment]
@lucernae  We need a test for this before we merge.

We need to test the following

force_ssl=true with self signed certificate. 
Force_ssl=true with snake oil certificates
Force_ssl=true with certificate from a CA authority

I will attempt this

**Comment by lucernae** [comment]
Wasn't GitHub markdown already scans TOC now? :p

> Force_ssl=true with certificate from a CA authority

I am not sure how to attempt this one. If we want to use Letsencrypt, we should prepare a real certificate from a given domain name (such as `postgis.kartoza.com`). However, I've not found a solution to transport this certificate (it will need a private key) to GitHub Action in a safe way.

**Comment by NyakudyaA** [comment]
> Wasn't GitHub markdown already scans TOC now? :p
I don't understand what you mean here. 
> 
> > Force_ssl=true with certificate from a CA authority
> 
> I am not sure how to attempt this one. If we want to use Letsencrypt, we should prepare a real certificate from a given domain name (such as `postgis.kartoza.com`). However, I've not found a solution to transport this certificate (it will need a private key) to GitHub Action in a safe way.

I think for now we can skip the test using a certificate from a CA authority because It will just be the same as using the self-signed certificate till we find a solution

**Comment by lucernae** [comment]
You can use self-signed with x509 structure and store it using PEM format, so that it will be the same structure/format with letsencrypt.

**Comment by lucernae** [comment]
> Wasn't GitHub markdown already scans TOC now? :p
> I don't understand what you mean here.

Ah sorry I didn't read this part because it was indented out.
GitHub markdown Readme viewer now provides a TOC like this:

image

I'm just teasing because even though GitHub provided a ToC shortcut, it's still better to generate it inside the Readme. As you can see, the GitHub default is not wide enough.

**Comment by NyakudyaA** [comment]
> > Wasn't GitHub markdown already scans TOC now? :p
> > I don't understand what you mean here.
> 
> Ah sorry I didn't read this part because it was indented out.
> GitHub markdown Readme viewer now provides a TOC like this:
> 
> image
> 
> I'm just teasing because even though GitHub provided a ToC shortcut, it's still better to generate it inside the Readme. As you can see, the GitHub default is not wide enough.


haha ha ha ha, Github is upping its game, soon they will be doing everything for us

**Pull request merged**
