### PR TITLE
Implement conf lock file check

### PR DESCRIPTION
**Pull request by lucernae**
It will make sure that the conf file will only be generated once
for a given container.

### CODE REVIEW

**Comment by lucernae** [comment]
@NyakudyaA I implement the lock file check from each setup that needs to modify a given conf file.

**Comment by NyakudyaA** [comment]
Thanks @lucernae I will wait for the test to pass and then test on my local - then merge. Thanks

**Comment by lucernae** [comment]
Thanks @NyakudyaA !

**Comment by AaronBrooksCsiro** [comment]
Is there a different location we can put the entry-point lock? I prefer to bind an entire directory to `/docker-entrypoint-initdb.d` and the current configuration puts the lockfile there, so when I remove the existing container and create fresh it doesn't execute the scripts.

**Comment by lucernae** [comment]
@AaronBrooksCsiro the lock file here is to make sure the conf file were initialized once.
I'm not sure of what you are trying to do, but if you mean you want "your script" to be executed once, your script should have your own lock file. Then you can put the lock on your mounted directory.

In our case,  the lock file is used to tell us that we already modified postgres conf. When the container start fresh, the conf file were reset, and we had to reinit the conf file based on environment variable that we choose for that container (it might be new/different), so this was intended. If you somehow don't want this behaviour, you can mount the ROOT_CONF directory so it doesn't get destroyed if the container is fresh. But then again, you can reinit your conf with new environment variables in this case, you had to change the conf file by yourself, since the entrypoint will skip it.

**Comment by NyakudyaA** [comment]
@lucernae I think he is referring to the following https://github.com/kartoza/docker-postgis/blob/develop/docker-entrypoint.sh#L20. The logic allows people to mount sql scripts and execute them when the container starts. If the location of the lock file affects running of SQL scripts we can change it and see if it fixes your problem.  @AaronBrooksCsiro can you test your workflow by putting changing https://github.com/kartoza/docker-postgis/blob/develop/docker-entrypoint.sh#L20
`SETUP_LOCKFILE="/docker-entrypoint-initdb.d/.entry_point.lock"`
to `SETUP_LOCKFILE="/.entry_point.lock"` and do a PR

**Pull request merged**
